#!/usr/bin/awk -f
# TRAFFIC MATRIX PTT-MG

BEGIN{ lastInt = 0; map = "awk -f foo.awk AS_map2.txt -" }
/unixSecondsUTC/{ 
  currentInt = $2 - ($2 % 10);
  if(currentInt != lastInt) {
    for(key in count) {
#      print "matrizTroca." key "." count[key] " " strftime("%R", lastInt) " " key " " count[key];
      print ("matrizTroca." key "." count[key] " " lastInt) | map; # > "saida."currentInt;
    }
    lastInt = currentInt;
    delete count;
  }
}

/out_vlan/{ outVlan = $2; }
/srcMAC/{ srcMAC = $2; }
/sampledPacketSize/{ sampledPacketSize = $2; }
/dstMAC/{
  key = srcMAC "." $2;
  if(outVlan = 10) {
    count[key] = count[key] + sampledPacketSize;
  }
}
END{}
